spring:
  cloud:
    gateway:
      routes:
        - id: my-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/my-service/**
        - id: another-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/another-service/**
  main:
    web-application-type: reactive
